version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    container_name: ipfs_host
    volumes:
      - ./export:/export
      - ./ipfs_data:/data/ipfs
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
    command: ["daemon", "--enable-pubsub-experiment"]
  server:
    build: ./server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    command: ["yarn", "start"]
